"""create phase 1 schema

Revision ID: 2cbec45ccc3d
Revises:
Create Date: 2026-05-09 18:25:46.505720
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "2cbec45ccc3d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cves",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("affected_products", sa.JSON(), nullable=False),
        sa.Column("references", sa.JSON(), nullable=False),
        sa.Column("last_enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exploit_intel_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column(
            "source_class",
            sa.Enum(
                "vulnerability_enrichment",
                "exploit_intelligence_metadata",
                "combined",
                name="intel_source_class",
            ),
            nullable=False,
        ),
        sa.Column(
            "edition_required",
            sa.Enum("ce", "enterprise", name="intel_edition_required"),
            nullable=False,
        ),
        sa.Column("built_in", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("encrypted_api_key_ref", sa.String(length=512), nullable=True),
        sa.Column(
            "last_health_status",
            sa.Enum("unknown", "healthy", "degraded", "failed", name="health_status"),
            nullable=False,
        ),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_system_role", sa.Boolean(), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "targets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("locator", sa.String(length=2048), nullable=False),
        sa.Column(
            "locator_type",
            sa.Enum("host", "ip", "domain", "url", "cidr", name="target_locator_type"),
            nullable=False,
        ),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("in_authorized_scope", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_targets_locator"), "targets", ["locator"], unique=False)
    op.create_table(
        "exploit_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cve_id", sa.String(length=32), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "nvd",
                "searchsploit",
                "vulncheck",
                "rapid7",
                "vulners",
                "vuldb",
                "armis",
                "mitre",
                name="intel_provider",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("disclosure_date", sa.Date(), nullable=True),
        sa.Column("exploit_type", sa.String(length=120), nullable=True),
        sa.Column("reliability_rating", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cve_id"],
            ["cves.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("mfa_enrolled", sa.Boolean(), nullable=False),
        sa.Column("mfa_secret", sa.String(length=512), nullable=True),
        sa.Column(
            "theme_preference", sa.Enum("dark", "light", name="theme_preference"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=200), nullable=False),
        sa.Column("resource_type", sa.String(length=120), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column(
            "outcome", sa.Enum("success", "failure", "denied", name="audit_outcome"), nullable=False
        ),
        sa.Column("source_ip", sa.String(length=64), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=False),
        sa.Column("entry_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "legal_acknowledgments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "eula",
                "acceptable_use_policy",
                "privacy_policy",
                "self_hosted_addendum",
                name="legal_document_type",
            ),
            nullable=False,
        ),
        sa.Column("document_version_hash", sa.String(length=64), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_ip", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "licenses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("edition", sa.Enum("ce", "enterprise", name="license_edition"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "expired", "invalid", "revoked", name="license_status"),
            nullable=False,
        ),
        sa.Column("issued_to", sa.String(length=255), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("installation_id", sa.String(length=255), nullable=False),
        sa.Column("feature_flags", sa.JSON(), nullable=False),
        sa.Column("signature", sa.Text(), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("imported_by", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["imported_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "report_exports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("format", sa.Enum("csv", "json", "pdf", name="report_format"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "succeeded", "failed", "expired", name="export_status"),
            nullable=False,
        ),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("storage_ref", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scanner_integrations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "scanner_type",
            sa.Enum(
                "nessus",
                "tenable_sc",
                "greenbone",
                "burp_enterprise",
                "bloodhound",
                "qualys",
                "insightvm",
                name="scanner_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "edition_required", sa.Enum("ce", "enterprise", name="edition_required"), nullable=False
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("encrypted_credentials_ref", sa.String(length=512), nullable=False),
        sa.Column("schedule", sa.JSON(), nullable=True),
        sa.Column(
            "last_sync_status",
            sa.Enum("never_run", "queued", "running", "succeeded", "failed", name="sync_status"),
            nullable=False,
        ),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("date_format", sa.String(length=40), nullable=False),
        sa.Column("default_landing_page", sa.String(length=120), nullable=False),
        sa.Column("table_state", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "scans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scanner_integration_id", sa.Uuid(), nullable=False),
        sa.Column("scanner_type", sa.String(length=80), nullable=False),
        sa.Column("scanner_scan_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "succeeded", "failed", "canceled", name="scan_status"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_output_ref", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(
            ["scanner_integration_id"],
            ["scanner_integrations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("scanner_finding_id", sa.String(length=255), nullable=True),
        sa.Column("dedupe_key", sa.String(length=64), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("critical", "high", "medium", "low", "info", name="finding_severity"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "acknowledged",
                "false_positive",
                "remediated",
                "risk_accepted",
                name="finding_status",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("protocol", sa.String(length=40), nullable=True),
        sa.Column("service_name", sa.String(length=120), nullable=True),
        sa.Column(
            "confidence",
            sa.Enum("confirmed", "likely", "potential", "unknown", name="finding_confidence"),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.Uuid(), nullable=True),
        sa.Column("tool_specific_data", sa.JSON(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_dedupe_key"), "findings", ["dedupe_key"], unique=False)
    op.create_table(
        "scan_targets",
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
        ),
        sa.PrimaryKeyConstraint("scan_id", "target_id"),
    )
    op.create_table(
        "finding_cves",
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("cve_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["cve_id"],
            ["cves.id"],
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
        ),
        sa.PrimaryKeyConstraint("finding_id", "cve_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("finding_cves")
    op.drop_table("scan_targets")
    op.drop_index(op.f("ix_findings_dedupe_key"), table_name="findings")
    op.drop_table("findings")
    op.drop_table("scans")
    op.drop_table("user_preferences")
    op.drop_table("scanner_integrations")
    op.drop_table("report_exports")
    op.drop_table("notifications")
    op.drop_table("licenses")
    op.drop_table("legal_acknowledgments")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("exploit_records")
    op.drop_index(op.f("ix_targets_locator"), table_name="targets")
    op.drop_table("targets")
    op.drop_table("roles")
    op.drop_table("exploit_intel_sources")
    op.drop_table("cves")
    # ### end Alembic commands ###
